package com.zmastery.english.data

import android.content.Context
import androidx.datastore.core.DataStore
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import kotlinx.coroutines.flow.first
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

// Single DataStore instance for the whole app.
private val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = "zmastery_store")

/**
 * Full serializable snapshot of everything the learner has created / progressed:
 * imported courses, lessons, vocabulary (with FSRS state) and profile stats.
 * Persisted as a single JSON blob so nothing is ever lost on app exit.
 */
@Serializable
data class AppState(
    val courses: List<CourseDto> = emptyList(),
    /** المسارات التخصصية (id ≥ 4) — registry محفوظ ومتزامن مع أي نسخة قديمة. */
    val customLevels: List<LevelDto> = emptyList(),
    val lessons: List<LessonDto> = emptyList(),
    val vocab: List<WordDto> = emptyList(),
    val profile: ProfileDto = ProfileDto(),
    val aiAgents: List<AiAgentDto> = emptyList(),
    /** Catalogue last fetched for the active key — survives app restarts. */
    val aiModels: List<AiModelDto> = emptyList(),
    val apiKeys: List<ApiKeyDto> = emptyList(),
    val exams: List<ExamRecordDto> = emptyList(),
    /** wordId -> exam miss count (stored as string keys for JSON safety). */
    val examMisses: Map<String, Int> = emptyMap(),
    /** Unified story archive: daily stories + reading-lesson stories. */
    val stories: List<StoryDto> = emptyList(),
    /** أهداف المتعلم التطبيقية (القصة اليومية تُنسج حولها). */
    val goals: List<LifeGoal> = emptyList(),
    /** One row per calendar day of activity — powers analytics + the coach. */
    val dayStats: List<DayStat> = emptyList(),
    /** Active study plan configuration (roadmap). */
    val studyPlan: StudyPlanDto = StudyPlanDto(),
    /** Cached AI-coach reports, keyed by scope name. */
    val coachReports: List<CoachReport> = emptyList(),
    /** Seven Seals: chests the learner has actually opened. */
    val chests: List<ChestRecord> = emptyList(),
    /**
     * الصناديق الغامضة — الحالة الكاملة لكل صندوق (مستحق/مفتوح/خامل).
     * خفيفة جداً: نصوص وأرقام فقط، لا صور ولا ملفات.
     */
    val mysteryRewards: List<MysteryReward> = emptyList(),
    /** Perks currently owned (freezes, themes, zones, badges…). */
    val wallet: PerkWallet = PerkWallet(),
    /** المرحلة الثالثة — تقارير مرآة الإدراك المولّدة، مفتاحها معرّف الصندوق. */
    val mirrorReports: Map<String, MirrorReport> = emptyMap(),
    /**
     * المرحلة الثالثة — التيليمتري السلوكي الذي تُبنى عليه مرآة الإدراك.
     * مضغوط جداً: نحتفظ بآخر 400 حدث فقط (≈20 كيلوبايت) وهو أكثر من كافٍ
     * لاستقرار كل المؤشرات الإحصائية، فلا ينتفخ ملف الحالة أبداً.
     */
    val reviewSignals: List<ReviewSignalDto> = emptyList(),
    /** ساعات المراجعة (0..23) لاستخراج ساعة الذروة — آخر 400 قيمة. */
    val reviewHours: List<Int> = emptyList(),
    /** المرحلة الرابعة — مهمة الإنقاذ النشطة بعد انكسار السلسلة. */
    val rescue: RescueMission = RescueMission(),
    /** آخر يوم عُرضت فيه مهمة إنقاذ (يمنع تكرار العرض في نفس اليوم). */
    val lastRescueOfferDay: Long = 0L,
    /** أعلى سلسلة سُجّلت قبل الانكسار — تُستخدم للاستعادة. */
    val streakBeforeBreak: Int = 0,
    val version: Int = 1,
)

/**
 * أخف تمثيل ممكن لحدث مراجعة واحد — الحقول التي تحتاجها مرآة الإدراك فقط.
 * (لا نحفظ ReviewLog كاملاً: retrievability/stability لا يستخدمها التحليل.)
 */
@Serializable
data class ReviewSignalDto(
    val wordId: Int = 0,
    val grade: Int = 0,
    val stage: Int = 0,
    val replays: Int = 0,
    val timeMs: Long = 0L,
)

@Serializable
data class StoryDto(
    val id: Int, val kind: String, val title: String, val en: String, val ar: String,
    val words: List<String> = emptyList(), val dayEpoch: Long = 0L, val dateLabel: String = "",
    val lessonId: Int = 0, val courseName: String = "",
    val isRead: Boolean = false, val isFavorite: Boolean = false,
    // ----- مسار الهدف التطبيقي (افتراضية = الأرشيف القديم يُقرأ بلا فقدان) -----
    val goalId: String = "", val goalStage: String = "",
    val contextQuestionEn: String = "", val contextQuestionAr: String = "",
    val contextAnswer: String = "",
    /** Whether this story's full narration was permanently generated by AI TTS. */
    val audioReady: Boolean = false,
)

@Serializable
data class AiAgentDto(
    val id: String, val modelId: String, val character: String,
    val voiceId: String, val style: String, val prompt: String,
)

/** Persisted catalogue entry — compact, defaults keep old backups readable. */
@Serializable
data class AiModelDto(
    val id: String,
    val displayName: String = "",
    val kind: String = "TEXT",
    val description: String = "",
    val methods: List<String> = emptyList(),
    val inputTokenLimit: Int = 0,
    val outputTokenLimit: Int = 0,
    val version: String = "",
    val apiVersions: List<String> = emptyList(),
    val fetched: Boolean = false,
) {
    fun toDomain(): AiModel = AiModel(
        id = id,
        displayName = displayName.ifBlank { id },
        kind = runCatching { ModelKind.valueOf(kind) }.getOrDefault(ModelKind.OTHER),
        description = description,
        methods = methods,
        inputTokenLimit = inputTokenLimit,
        outputTokenLimit = outputTokenLimit,
        version = version,
        apiVersions = apiVersions,
        fetched = fetched,
    )
}

fun AiModel.toDto(): AiModelDto = AiModelDto(
    id = id,
    displayName = displayName,
    kind = kind.name,
    description = description,
    methods = methods,
    inputTokenLimit = inputTokenLimit,
    outputTokenLimit = outputTokenLimit,
    version = version,
    apiVersions = apiVersions,
    fetched = fetched,
)

@Serializable
data class ApiKeyDto(
    val id: String, val label: String, val provider: String,
    /** Legacy field (masked). Kept so old backups still deserialize. */
    val maskedKey: String = "",
    val active: Boolean = false,
    /** The real secret — required for the key to actually authenticate. */
    val rawKey: String = "",
    /** Custom endpoint for OpenAI-compatible providers. */
    val baseUrl: String = "",
    val status: String = "",
)

@Serializable
data class CourseDto(
    val id: Int, val levelId: Int, val name: String, val type: String,
    val target: Int, val accent: Long, val style: String, val key: String, val jsonId: String,
)

/**
 * مستوى تخصصي ديناميكي (id ≥ 4) — يُنشأ تلقائياً من بيانات المناهج المستوردة
 * (level + level_name داخل JSON الدرس) ويظهر في شاشة المستويات كمسار مستقل.
 */
@Serializable
data class LevelDto(
    val id: Int = 0,
    val name: String = "",
    val description: String = "",
    val emoji: String = "🎯",
)

@Serializable
data class LessonDto(
    val id: Int, val courseId: Int, val no: Int, val title: String,
    val summaryAr: String, val readingEn: String, val readingAr: String,
    val keyPoints: List<String>, val isCompleted: Boolean,
    val dialogues: List<DialogueDto>, val newWordIds: List<Int>,
    val keySentences: List<SentenceDto>, val notes: List<String>, val quiz: List<QuizDto>,
    val reviewCount: Int, val lastMastery: Int, val dueInDays: Int, val intervalDays: Int,
    // raw rich JSON preserved verbatim so specialized viewers (phonetics, etc.)
    // can render every field the author uploaded — nothing is dropped.
    val rawJson: String = "",
    // ----- Rich lesson content (every field below is defaulted so backups -----
    // ----- created before this fix still deserialize without data loss). -----
    /** Conversation-course expressions. */
    val keyExpressions: List<KeyExpressionDto> = emptyList(),
    // ----- Grammar-course content -----
    val explanationAr: String = "",
    val logicAr: String = "",
    val examples: List<SentenceDto> = emptyList(),
    // ----- Reading-course content -----
    val fullTextEn: String = "",
    val fullTextAr: String = "",
    val segments: List<SentenceDto> = emptyList(),
    // ----- Writing-course content -----
    val topicEn: String = "",
    val topicAr: String = "",
    val brainstorming: List<BrainstormDto> = emptyList(),
    val guidedSentences: List<SentenceDto> = emptyList(),
    val finalDraft: SentenceDto? = null,
    // ----- AI audio generation state -----
    val audioReady: Boolean = false,
    // ----- حالة النشر السحابي (شارة «تم الرفع») — بحقول اختيارية حتى تبقى ----
    // ----- النسخ الاحتياطية القديمة تُقرأ بلا أي فقدان. ----
    /** لحظة التأكد من وجود الدرس في السحابة (0 = لم يُرفع). */
    val publishedAtMillis: Long = 0L,
    /** معرّف مستند Firestore الخاص بالدرس. */
    val publishedDocId: String = "",
)

@Serializable
data class DialogueDto(val speaker: String, val en: String, val ar: String)

@Serializable
data class SentenceDto(val en: String, val ar: String)

@Serializable
data class KeyExpressionDto(
    val expressionEn: String,
    val expressionAr: String,
    val usageAr: String = "",
)

@Serializable
data class BrainstormDto(
    val questionEn: String,
    val questionAr: String = "",
    val suggestedAnswerEn: String = "",
    val suggestedAnswerAr: String = "",
)

@Serializable
data class QuizDto(
    val type: String, val question: String, val options: List<String>,
    val answer: String, val explanationAr: String,
    /** audio_quiz: word to speak aloud before answering (defaulted: old backups load). */
    val audioText: String = "",
)

@Serializable
data class WordDto(
    val id: Int, val english: String, val arabic: String, val exampleEn: String,
    val exampleAr: String, val phonetic: String, val mentalImage: String, val courseId: Int,
    val stability: Double, val difficulty: Double, val phase: String, val dueInDays: Int,
    val intervalDays: Int, val lastReviewedDay: Long, val repetitions: Int, val mastered: Boolean,
    val listenCount: Int, val totalReviews: Int, val lapses: Int, val lastRecall: String,
    val avgRecallStage: Float, val lastGrade: Int, val pendingApproval: Boolean, val lessonId: Int,
    // ----- Rich analytics + AI audio state (defaulted: old backups still load) -----
    val totalTimeMs: Long = 0L,
    val lastRetrievability: Double = 0.0,
    val wordAudioReady: Boolean = false,
    val exampleAudioReady: Boolean = false,
)

@Serializable
data class ExamRecordDto(
    val id: String, val mode: String, val title: String,
    val correct: Int, val total: Int, val stamp: String, val durationMs: Long,
    val skillCorrect: Map<String, Int> = emptyMap(),
    val skillTotal: Map<String, Int> = emptyMap(),
)

@Serializable
data class ProfileDto(
    val streak: Int = 0, val xp: Int = 0, val totalReviewsToday: Int = 0,
    val dailyGoal: Int = 30, val lessonsPerDay: Int = 2, val studyHours: Double = 0.0,
    val motivationLevel: Float = 0f, val accuracy: Int = 0,
    val geminiApiKey: String = "", val ttsVoice: String = "Kore",
    val nextCourseId: Int = 1, val nextLessonId: Int = 1, val nextWordId: Int = 1,
    val desiredRetention: Double = 0.90, val maxIntervalDays: Int = 365,
    val revealMode: String = "FULL",
    // Auto-play the pronunciation when a review stage appears (all 4 stages).
    val reviewAutoPlay: Boolean = true,
    /**
     * When true, newly imported words/examples/lessons are queued for
     * permanent AI (Gemini) voice generation automatically in the background.
     * When false, nothing is auto-generated — the learner can still trigger
     * generation manually from the dashboard button. Either way, on-demand
     * listening ALWAYS works via the local offline engine — this toggle only
     * controls the permanent AI-narrated cache.
     */
    val autoGenerateAiAudio: Boolean = true,
    /**
     * MASTER switch for AI audio generation. When false, nothing is EVER
     * generated by Gemini (auto or manual) — only local instant playback
     * works. Distinct from [autoGenerateAiAudio], which only controls whether
     * generation auto-starts after an import.
     */
    val aiAudioEnabled: Boolean = true,
    // ----- Mnemonic (mental-link) image generation settings -----
    val mnemonicStyle: String = "CARTOON_3D",
    val mnemonicPersona: String = "NONE",
    val mnemonicModel: String = "GEMINI",
    val mnemonicNumbering: Boolean = false,
    val mnemonicBatchSize: Int = 16,
    // ----- Onboarding / mission screen -----
    val onboardingDone: Boolean = false,
    // Epoch-day of the most recently generated daily story (0 = none yet).
    val lastStoryDay: Long = 0L,
    val nextStoryId: Int = 1,
    // ----- Daily rollover -----
    /** Epoch-day the per-day counters (tasks / reviewsToday) belong to. */
    val lastActiveDay: Long = 0L,
    /** Serialized daily-task progress for [lastActiveDay]: "id:progress". */
    val dailyTaskProgress: List<String> = emptyList(),
    // ----- 3D Momentum: the daily micro-habit (الورد اليومي) -----
    /** Chosen micro-habit id. */
    val microHabitId: String = "micro_review",
    /** Progress on today's micro-habit (belongs to lastActiveDay). */
    val microHabitProgress: Int = 0,
    /** Learner's display name — personalises the AI wisdom cards. */
    val learnerName: String = "",
    /** Learner's email (for future Firebase Auth integration). */
    val learnerEmail: String = "",
    /** هل حُسب يوم [lastActiveDay] ضمن سلسلة الحماسة؟ */
    val dayEarnedStreak: Boolean = false,
    // ----- Cloud sync (Firestore) -----
    /** Epoch millis of the newest lesson document already pulled from the cloud. */
    val lastCloudLessonSyncMillis: Long = 0L,
    /** Master toggle: pull cloud lessons + push/pull progress automatically. */
    val cloudSyncEnabled: Boolean = true,
    /**
     * Web Client ID for Google Sign-In (from Firebase Console → Authentication
     * → Sign-in method → Google, once enabled). Empty = Google Sign-In hidden,
     * app still fully works via the automatic anonymous cloud account.
     */
    val googleWebClientId: String = "",
    /**
     * معرّف آخر إعلان أغلقه المستخدم — بدونه كان الإعلان يعود للظهور عند كل
     * إقلاع لأن الإغلاق كان في الذاكرة فقط.
     */
    val dismissedAnnouncementId: String = "",
    /**
     * فتح وضع المطور محلياً (بكود المسؤول). كان غير محفوظ، فكانت أدوات النشر
     * تختفي بعد كل إعادة تشغيل للتطبيق.
     */
    val developerUnlocked: Boolean = false,
    /** Keep the "free models only" filter across sessions. */
    val showFreeModelsOnly: Boolean = false,
)

object Persistence {
    private val json = Json { ignoreUnknownKeys = true; encodeDefaults = true }
    private val KEY = stringPreferencesKey("app_state_json")

    private val TAG = "ZMasteryPersistence"

    /** Serialize [state] to the same JSON shape used for local storage — also
     *  used as the cloud sync payload so both copies are always compatible. */
    fun encode(state: AppState): String = json.encodeToString(state)

    /** Parse a JSON blob (local or pulled from the cloud) back into [AppState]. */
    fun decode(raw: String): AppState? = runCatching { json.decodeFromString<AppState>(raw) }.getOrNull()

    suspend fun load(context: Context): AppState? {
        return try {
            val raw = context.dataStore.data.first()[KEY] ?: return null
            if (raw.isBlank()) {
                android.util.Log.w(TAG, "Stored data is blank")
                null
            } else {
                json.decodeFromString<AppState>(raw)
            }
        } catch (e: Exception) {
            android.util.Log.e(TAG, "Load failed: ${e.javaClass.simpleName}: ${e.message}", e)
            null
        }
    }

    suspend fun save(context: Context, state: AppState) {
        val raw = json.encodeToString(state)
        // Let exceptions propagate — the caller (DataGuard.safeSave) handles
        // them properly instead of silently losing data.
        context.dataStore.edit { it[KEY] = raw }
    }

    suspend fun clear(context: Context) {
        context.dataStore.edit { it.remove(KEY) }
    }
}
