package com.zmastery.english.data

/**
 * Unified story archive.
 *
 * Two very different things live side by side here, on purpose:
 *
 *  • DAILY  — a short story generated from the learner's OWN due words. It is
 *             the daily "consolidation ritual": yesterday's vocabulary comes
 *             back as a narrative, which is far stickier than isolated cards.
 *  • LESSON — the reading text that belongs to a lesson in a reading course.
 *             Every reading lesson has a story, so the archive doubles as the
 *             learner's personal library of everything they have ever read.
 *
 * Keeping both in one archive means there is exactly ONE place to go back and
 * re-read, which is what makes long-term review actually happen.
 */
enum class StoryKind(val label: String, val short: String) {
    DAILY("قصة اليوم", "يومية"),
    LESSON("قصة درس", "درس"),
}

/** How hard the text is, derived from sentence + word length. */
enum class StoryLevel(val label: String) {
    EASY("سهلة"),
    MEDIUM("متوسطة"),
    HARD("متقدمة"),
}

/**
 * One archived story.
 *
 * @param id          stable unique id
 * @param kind        daily vs lesson
 * @param title       display title
 * @param en          English body
 * @param ar          Arabic translation (may be blank for lesson texts)
 * @param words       the vocabulary this story was built around / teaches
 * @param dayEpoch    epoch-day the story belongs to (daily) or was added
 * @param dateLabel   pre-rendered date label
 * @param lessonId    source lesson (LESSON kind only, else 0)
 * @param courseName  source course name (LESSON kind only)
 * @param isRead      the learner marked it as read
 * @param isFavorite  pinned to the top of the archive
 */
data class ArchivedStory(
    val id: Int,
    val kind: StoryKind,
    val title: String,
    val en: String,
    val ar: String = "",
    val words: List<String> = emptyList(),
    val dayEpoch: Long = 0L,
    val dateLabel: String = "",
    val lessonId: Int = 0,
    val courseName: String = "",
    var isRead: Boolean = false,
    var isFavorite: Boolean = false,
    /** True once the full narration has been permanently generated by AI TTS. */
    var audioReady: Boolean = false,
    // ----- مسار الهدف التطبيقي (قيم افتراضية = القصص القديمة تُقرأ بلا فقدان) -----
    /** الهدف الذي نُسجت من أجله القصة ("" = قصة أكاديمية قديمة). */
    val goalId: String = "",
    /** اسم المرحلة التي كانت جارية عند التوليد. */
    val goalStage: String = "",
    /** سؤال السياق اليومي الذي يبني منه الـAI سياق المتعلم تدريجياً. */
    val contextQuestionEn: String = "",
    val contextQuestionAr: String = "",
    /** إجابة المتعلم عن سؤال السياق ("" = لم يُجب بعد). */
    val contextAnswer: String = "",
) {
    /** Word count of the English body. */
    val wordCount: Int get() = en.split(Regex("\\s+")).count { it.isNotBlank() }

    /** Rough minutes to read at ~130 wpm (learner pace, not native pace). */
    val readMinutes: Int get() = (wordCount / 130.0).let { if (it < 1.0) 1 else Math.round(it).toInt() }

    /** Difficulty estimated from average word length and sentence length. */
    val level: StoryLevel
        get() {
            val words = en.split(Regex("[^A-Za-z']+")).filter { it.isNotBlank() }
            if (words.isEmpty()) return StoryLevel.EASY
            val avgWord = words.sumOf { it.length }.toDouble() / words.size
            val sentences = en.split(Regex("[.!?]+")).count { it.isNotBlank() }.coerceAtLeast(1)
            val avgSentence = words.size.toDouble() / sentences
            val score = avgWord * 1.4 + avgSentence * 0.42
            return when {
                score < 12.0 -> StoryLevel.EASY
                score < 16.5 -> StoryLevel.MEDIUM
                else -> StoryLevel.HARD
            }
        }
}

/**
 * Builds the daily story locally — no network, no API key, always works.
 *
 * This is deliberately a *template* generator rather than an AI call: the daily
 * ritual must never fail or block on connectivity, because the whole product
 * thesis is consistency. When an AI key is configured the app can enrich the
 * text later, but the ritual itself is always available offline.
 */
object DailyStoryMaker {

    /** Narrative scaffolds. Each takes the words and weaves them in order. */
    private val openings = listOf(
        "This morning started quietly." to "بدأ هذا الصباح بهدوء.",
        "It was an ordinary Tuesday." to "كان يوماً عادياً من أيام الثلاثاء.",
        "The city was still waking up." to "كانت المدينة لا تزال تستيقظ.",
        "Rain tapped softly on the window." to "كان المطر يطرق النافذة بلطف.",
        "The bus was late again." to "تأخّر الباص مرة أخرى.",
        "Everything felt slower than usual." to "كان كل شيء أبطأ من المعتاد.",
        "The café smelled of fresh bread." to "كانت رائحة الخبز الطازج تفوح من المقهى.",
    )

    private val closings = listOf(
        "By evening, the day finally made sense." to "وبحلول المساء، صار لليوم معنى أخيراً.",
        "Small steps, but they counted." to "خطوات صغيرة، لكنها كانت مهمّة.",
        "Tomorrow would ask for the same patience." to "سيطلب الغد نفس الصبر.",
        "Nothing dramatic happened, and that was fine." to "لم يحدث شيء مثير، وكان ذلك جيداً.",
        "The habit held, one more day." to "صمدت العادة، يوماً آخر.",
        "It was enough for today." to "كان ذلك كافياً لهذا اليوم.",
    )

    /**
     * Weave [words] into a short story.
     *
     * @param words    the vocabulary to feature (their example sentences are reused
     *                 when available, which keeps the story grammatical)
     * @param dayEpoch epoch-day — also seeds the template choice so the same day
     *                 always yields the same story
     */
    fun compose(words: List<VocabWord>, dayEpoch: Long): Pair<String, String> {
        if (words.isEmpty()) return Pair("", "")
        val seed = (dayEpoch % 1000L).toInt()
        val (openEn, openAr) = openings[seed % openings.size]
        val (closeEn, closeAr) = closings[(seed / 3) % closings.size]

        val bodyEn = StringBuilder()
        val bodyAr = StringBuilder()
        words.forEach { w ->
            // Prefer the word's own example — it is already correct English.
            val sEn = w.exampleEn.trim().ifBlank { fallbackSentence(w.english) }
            val sAr = w.exampleAr.trim().ifBlank { "" }
            bodyEn.append(sEn.trimEnd('.', '!', '?')).append(". ")
            if (sAr.isNotBlank()) bodyAr.append(sAr.trimEnd('.', '!', '؟')).append(". ")
        }

        val en = "$openEn ${bodyEn.toString().trim()} $closeEn".trim()
        val ar = buildString {
            append(openAr).append(' ')
            append(bodyAr.toString().trim())
            if (bodyAr.isNotBlank()) append(' ')
            append(closeAr)
        }.trim()
        return Pair(en, ar)
    }

    private fun fallbackSentence(word: String): String =
        "Then someone mentioned the word \"$word\" and it stayed in my head"

    /** Title for a daily story, seeded by the day so it is stable. */
    fun title(dayEpoch: Long, count: Int): String {
        val titles = listOf(
            "يوم من كلماتي", "قصة الكلمات", "صفحة اليوم", "من دفتري",
            "حكاية قصيرة", "كلمات اليوم", "مشهد عادي",
        )
        return "${titles[(dayEpoch % titles.size).toInt()]} · $count كلمة"
    }

    /** Prompt for enriching the daily story with an AI model (optional path). */
    fun aiPrompt(words: List<VocabWord>, level: String = "A2-B1"): String {
        val list = words.joinToString(", ") { it.english }
        return """
            Write a short, natural English story of 6–8 sentences for an Arabic-speaking
            learner at $level level. Use ALL of these words naturally, in a way that makes
            each meaning obvious from context: $list.

            Rules:
            • Simple everyday setting, one small arc (beginning → small problem → resolution).
            • Short sentences. No idioms a learner would not know.
            • Do not define the words, do not use bold, do not list them.

            Then output the Arabic translation of the whole story after the line "---".
        """.trimIndent()
    }

    /**
     * برومبت «القصة نحو الهدف»: الموقف الحقيقي أولاً، والكلمات توابل اختيارية.
     *
     * قلبُ المعادلة المتفق عليه: لم تعد القصة خادمةً لجدول الـFSRS — بل تُنسج
     * حول مرحلة الهدف الحالية وبسياق المتعلم الذي يبنيه الـAI يوماً بيوم.
     * الكلمات المستحقة تُنسج بحدّ أقصى 3 وبشرط أن تخدم الموقف، وإلا تُترك.
     */
    fun goalPrompt(
        goalTitle: String,
        stage: String,
        contextLines: List<String>,
        words: List<String>,
        level: String = "A2-B1",
    ): String {
        val ctx = contextLines.takeLast(12).joinToString("\n") { "- $it" }
        val wordNote = if (words.isEmpty())
            "No target words are required today; the situation is everything."
        else
            "Optionally weave in UP TO 3 of these words, ONLY where they serve the " +
                "situation naturally (never force them): ${words.joinToString(", ")}."
        return """
            The learner is pursuing a REAL-LIFE language goal: "$goalTitle".
            Today's micro-stage of that goal: "$stage".
            Write a short, natural English story (6–9 short sentences, one small arc)
            depicting a realistic situation in which the learner PRACTISES exactly this
            stage — e.g. actually introducing themselves, describing a skill, handling
            a follow-up question. Make it feel like the learner's own life, at $level level.

            ${if (ctx.isNotBlank()) "What the model already knows about the learner (use it, and stay consistent):\n$ctx" else "You do not know the learner yet — keep the situation generic-professional."}

            $wordNote

            Rules:
            • The situation must move the learner's goal forward, not teach vocabulary.
            • Short sentences. No idioms a learner would not know. No bold, no lists.
            • End with ONE tiny "apply today" nudge inside the story's resolution
              (the character does the thing in real life).

            Return ONLY a JSON object with exactly these keys:
              "title"            : short catchy English title (max 6 words)
              "english"          : the story
              "arabic"           : fluent Modern Standard Arabic translation
              "context_question_en" : ONE small personal question (1 sentence) that,
                                      answered, tells you more about the learner's real
                      life/skills for tomorrow's story
              "context_question_ar" : its Arabic translation
            No markdown, no code fences. Raw JSON only.
        """.trimIndent()
    }
}
