package com.zmastery.english.audio

import android.content.Context
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.net.ConnectivityManager
import android.net.NetworkCapabilities
import android.os.Bundle
import android.speech.tts.TextToSpeech
import android.speech.tts.UtteranceProgressListener
import android.util.Base64
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.io.File
import java.net.HttpURLConnection
import java.net.URL
import java.util.Locale
import kotlin.coroutines.resume

/**
 * English text-to-speech engine — TWO completely separate paths, never mixed:
 *
 *  1. INSTANT (local only, never saved): [speakInstant] — used everywhere the
 *     learner taps a speaker icon to hear something right now (review,
 *     exams, vocabulary lists, lesson readers…). This ALWAYS uses Android's
 *     built-in offline engine and NEVER calls Gemini, NEVER writes a
 *     permanent cache file. The only exception: if a clip for that exact text
 *     was already permanently generated by AI before, we just play that file
 *     (no new AI call is made — it is simply reusing existing audio).
 *
 *  2. PERMANENT (AI only, always saved): [generateAndCachePermanent] and
 *     [generateLongFormAndCache] — used by the explicit "generate audio"
 *     flows (auto after import, or a manual button). These call Gemini's
 *     neural TTS ONLY. If Gemini is unavailable (no key / offline / request
 *     failed) they return false and generate NOTHING — there is deliberately
 *     NO fallback to the local engine here, so a permanently cached clip is
 *     always a genuine neural voice, never a robotic one.
 */
class TtsManager(context: Context) {

    private val appContext = context.applicationContext

    // ---- state observable by UI ----
    var speakingKey by mutableStateOf<String?>(null)   // which item is playing
        private set
    var engineReady by mutableStateOf(false)
        private set

    // ---- config ----
    @Volatile var apiKey: String = ""
    @Volatile var voice: String = "Kore"   // Gemini prebuilt voice name

    // ---- Android TTS (instant / temporary path only) ----
    private var androidTts: TextToSpeech? = null

    init {
        androidTts = TextToSpeech(appContext) { status ->
            if (status == TextToSpeech.SUCCESS) {
                androidTts?.language = Locale.US
                androidTts?.setSpeechRate(0.95f)
                engineReady = true
            }
        }
    }

    /** True if a Gemini key is configured (enables neural voices). */
    val hasGeminiKey: Boolean get() = apiKey.isNotBlank()

    /** Directory where PERMANENT AI-generated audio clips live. */
    private val audioDir: File by lazy {
        File(appContext.cacheDir, "z_audio").apply { mkdirs() }
    }

    /** True when the device currently has a working internet connection. */
    fun isOnline(): Boolean {
        return try {
            val cm = appContext.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
            val net = cm.activeNetwork ?: return false
            val caps = cm.getNetworkCapabilities(net) ?: return false
            caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET) &&
                caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED)
        } catch (e: Exception) {
            false
        }
    }

    /** Stable cache file for a piece of text (keyed by content + voice). */
    private fun cacheFileFor(text: String): File {
        val hash = (text.trim().lowercase() + "|" + voice).hashCode()
        return File(audioDir, "clip_${hash}.wav")
    }

    /** True if a PERMANENT AI clip for [text] already exists on disk. */
    fun isCached(text: String): Boolean {
        val f = cacheFileFor(text)
        return f.exists() && f.length() > 44L // header + some data
    }

    /** Delete the permanent AI clip for [text] from disk (used by "regenerate all"). */
    fun evictCache(text: String) {
        val f = cacheFileFor(text)
        if (f.exists()) runCatching { f.delete() }
    }

    /** Wipe every permanently cached AI clip. Used for a full "regenerate all". */
    fun evictAllCache() {
        runCatching { audioDir.listFiles()?.forEach { it.delete() } }
    }

    // ==================================================================
    //  1) INSTANT — local engine only, never persisted, never AI.
    // ==================================================================

    /**
     * Speak [text] right now for on-demand listening (review card, exam
     * question, dictionary entry…). Reuses a previously AI-generated
     * permanent clip if one already exists for this exact text (free, no new
     * AI call) — otherwise speaks it live through the local offline engine.
     * This function NEVER calls Gemini and NEVER writes to the permanent
     * cache itself.
     */
    suspend fun speakInstant(text: String, key: String) {
        val clean = text.trim()
        if (clean.isEmpty()) return
        speakingKey = key
        try {
            val cached = cacheFileFor(clean)
            if (cached.exists() && cached.length() > 44L) {
                withContext(Dispatchers.IO) { playFile(cached) }
            } else {
                androidSpeakBlocking(clean)
            }
        } finally {
            speakingKey = null
        }
    }

    /** Alias kept for call sites that only ever want the permanent clip. */
    suspend fun playCached(text: String, key: String) = speakInstant(text, key)

    fun stop() {
        androidTts?.stop()
        speakingKey = null
    }

    fun shutdown() {
        androidTts?.stop()
        androidTts?.shutdown()
        androidTts = null
    }

    /** Speak (and await completion) via the local Android engine only. */
    private suspend fun androidSpeakBlocking(text: String) {
        val tts = androidTts ?: return
        if (!engineReady) return
        val maxLen = runCatching { TextToSpeech.getMaxSpeechInputLength() }
            .getOrDefault(4000).coerceAtLeast(500)
        val chunks = splitForTts(text, maxChars = (maxLen - 50).coerceAtLeast(200))
        if (chunks.isEmpty()) return
        for ((idx, chunk) in chunks.withIndex()) {
            val done = suspendCancellableCoroutine<Boolean> { cont ->
                val id = "instant_${System.currentTimeMillis()}_$idx"
                tts.setOnUtteranceProgressListener(object : UtteranceProgressListener() {
                    override fun onStart(utteranceId: String?) {}
                    override fun onDone(utteranceId: String?) {
                        if (cont.isActive) cont.resume(true)
                    }
                    @Deprecated("deprecated")
                    override fun onError(utteranceId: String?) {
                        if (cont.isActive) cont.resume(false)
                    }
                    override fun onError(utteranceId: String?, errorCode: Int) {
                        if (cont.isActive) cont.resume(false)
                    }
                })
                cont.invokeOnCancellation { runCatching { tts.stop() } }
                val params = Bundle().apply { putString(TextToSpeech.Engine.KEY_PARAM_UTTERANCE_ID, id) }
                val mode = if (idx == 0) TextToSpeech.QUEUE_FLUSH else TextToSpeech.QUEUE_ADD
                val res = tts.speak(chunk, mode, params, id)
                if (res != TextToSpeech.SUCCESS && cont.isActive) cont.resume(false)
            }
            if (!done) break
        }
    }

    private fun playFile(f: File) {
        val mp = MediaPlayer()
        try {
            mp.setDataSource(f.absolutePath)
            mp.setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_MEDIA)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
                    .build()
            )
            mp.prepare()
            mp.start()
            while (mp.isPlaying) Thread.sleep(80)
        } catch (e: Exception) {
            // ignore — playback best-effort
        } finally {
            runCatching { mp.release() }
        }
    }

    // ==================================================================
    //  2) PERMANENT — Gemini AI only, always saved, NO local fallback.
    // ==================================================================

    /**
     * Generate + permanently cache short text (a word, an example sentence)
     * using Gemini neural TTS ONLY. Returns true on success. If Gemini is
     * unavailable or the request fails, returns false — nothing is written,
     * and the item stays "pending" so it can be retried later. There is
     * deliberately NO fallback to the local engine: a permanent clip is only
     * ever a genuine AI voice.
     */
    suspend fun generateAndCachePermanent(text: String): Boolean {
        val clean = text.trim()
        if (clean.isEmpty()) return true
        if (isCached(clean)) return true
        if (!hasGeminiKey || !isOnline()) return false
        val pcm = withContext(Dispatchers.IO) { runCatching { geminiPcm(clean) }.getOrNull() }
            ?: return false
        if (pcm.isEmpty()) return false
        return withContext(Dispatchers.IO) {
            runCatching { writeWav(cacheFileFor(clean), pcm, 24000); true }.getOrDefault(false)
        }
    }

    /**
     * Generate a LONG passage (a story, a full lesson reading text) as ONE
     * continuous, permanently cached clip. The text is split on sentence
     * boundaries to respect the TTS request size, each chunk is synthesized
     * by Gemini, and the raw PCM is concatenated before writing a single WAV
     * — so playback is one seamless clip, not separate fragments. AI only,
     * same no-fallback rule as [generateAndCachePermanent].
     */
    suspend fun generateLongFormAndCache(text: String): Boolean {
        val clean = text.trim()
        if (clean.isEmpty()) return true
        if (isCached(clean)) return true
        if (!hasGeminiKey || !isOnline()) return false
        val chunks = splitForTts(clean, maxChars = 700)
        if (chunks.isEmpty()) return false
        val all = ByteArrayOutputStream()
        for (chunk in chunks) {
            val pcm = withContext(Dispatchers.IO) { runCatching { geminiPcm(chunk) }.getOrNull() }
                ?: return false
            all.write(pcm)
        }
        val bytes = all.toByteArray()
        if (bytes.isEmpty()) return false
        return withContext(Dispatchers.IO) {
            runCatching { writeWav(cacheFileFor(clean), bytes, 24000); true }.getOrDefault(false)
        }
    }

    /** Greedily pack sentences into chunks no longer than [maxChars]. */
    private fun splitForTts(text: String, maxChars: Int): List<String> {
        val sentences = text.split(Regex("(?<=[.!?])\\s+")).filter { it.isNotBlank() }
        if (sentences.isEmpty()) return if (text.isNotBlank()) listOf(text.take(maxChars)) else emptyList()
        val chunks = mutableListOf<String>()
        val cur = StringBuilder()
        for (s in sentences) {
            val piece = if (s.length > maxChars) s.take(maxChars) else s
            if (cur.length + piece.length + 1 > maxChars && cur.isNotEmpty()) {
                chunks.add(cur.toString().trim())
                cur.setLength(0)
            }
            cur.append(piece).append(' ')
        }
        if (cur.isNotEmpty()) chunks.add(cur.toString().trim())
        return chunks
    }

    /** Wrap raw 16-bit PCM mono bytes into a minimal WAV container. */
    private fun writeWav(out: File, pcm: ByteArray, sampleRate: Int) {
        val channels = 1
        val bitsPerSample = 16
        val byteRate = sampleRate * channels * bitsPerSample / 8
        val totalDataLen = pcm.size + 36
        out.outputStream().use { os ->
            fun writeInt(v: Int) {
                os.write(v and 0xff); os.write((v shr 8) and 0xff)
                os.write((v shr 16) and 0xff); os.write((v shr 24) and 0xff)
            }
            fun writeShort(v: Int) { os.write(v and 0xff); os.write((v shr 8) and 0xff) }
            os.write("RIFF".toByteArray()); writeInt(totalDataLen); os.write("WAVE".toByteArray())
            os.write("fmt ".toByteArray()); writeInt(16); writeShort(1); writeShort(channels)
            writeInt(sampleRate); writeInt(byteRate); writeShort(channels * bitsPerSample / 8)
            writeShort(bitsPerSample)
            os.write("data".toByteArray()); writeInt(pcm.size); os.write(pcm)
        }
    }

    // ---------------------------------------------------------------
    // Gemini TTS — returns raw 24kHz mono 16-bit PCM bytes
    // ---------------------------------------------------------------
    private fun geminiPcm(text: String): ByteArray? {
        val url = URL(
            "https://generativelanguage.googleapis.com/v1beta/models/" +
                "gemini-2.5-flash-preview-tts:generateContent?key=$apiKey"
        )
        val body = JSONObject().apply {
            put("contents", org.json.JSONArray().put(JSONObject().apply {
                put("parts", org.json.JSONArray().put(JSONObject().apply {
                    // Ask for clear, natural English pronunciation
                    put("text", "Say clearly in a natural English accent: $text")
                }))
            }))
            put("generationConfig", JSONObject().apply {
                put("responseModalities", org.json.JSONArray().put("AUDIO"))
                put("speechConfig", JSONObject().apply {
                    put("voiceConfig", JSONObject().apply {
                        put("prebuiltVoiceConfig", JSONObject().apply {
                            put("voiceName", voice)
                        })
                    })
                })
            })
        }.toString()

        val conn = (url.openConnection() as HttpURLConnection).apply {
            requestMethod = "POST"
            connectTimeout = 15000
            readTimeout = 20000
            doOutput = true
            setRequestProperty("Content-Type", "application/json")
        }
        conn.outputStream.use { it.write(body.toByteArray(Charsets.UTF_8)) }

        val code = conn.responseCode
        val stream = if (code in 200..299) conn.inputStream else conn.errorStream
        val resp = stream?.bufferedReader()?.use { it.readText() } ?: return null
        if (code !in 200..299) return null

        // Navigate: candidates[0].content.parts[0].inlineData.data (base64 PCM)
        return try {
            val root = JSONObject(resp)
            val parts = root.getJSONArray("candidates").getJSONObject(0)
                .getJSONObject("content").getJSONArray("parts")
            for (i in 0 until parts.length()) {
                val p = parts.getJSONObject(i)
                if (p.has("inlineData")) {
                    val b64 = p.getJSONObject("inlineData").getString("data")
                    return Base64.decode(b64, Base64.DEFAULT)
                }
            }
            null
        } catch (e: Exception) {
            null
        }
    }
}
